if test -x /opt/homebrew/bin/brew; then
	eval "$(/opt/homebrew/bin/brew shellenv)"
fi

if test -x /home/linuxbrew/.linuxbrew/bin/brew; then
	eval "$(/home/linuxbrew/.linuxbrew/bin/brew)"
fi

source $HOME/.config/zsh/aliases.zsh

if [ "$TERM_PROGRAM" != "WarpTerminal" ]; then

	export ZSH="$HOME/.oh-my-zsh"
	ZSH_THEME="nebula"
	source $ZSH/oh-my-zsh.sh
	source $HOME/.zi/bin/zi.zsh
	autoload -Uz _zi
	(( ${+_comps} )) && _comps[zi]=_zi
	source $HOME/.config/zsh/plugins.zsh
	source $HOME/.config/zsh/vi.zsh
	source $HOME/.config/zsh/fzf.zsh
fi

plugins=(git extract 1password)

source $HOME/.cargo/env
source $HOME/.config/zsh/env.zsh
source $HOME/.config/zsh/joshuto.zsh
source $HOME/.config/zsh/yazi.zsh

# 1Password
if [[ "$(uname)" == "Darwin" ]]; then
	eval "$(op completion zsh)"
fi

